### ISSUE TITLE
Tests for mkdir and touch fail

### ISSUE THREAD

**Issue by faraazahmad** [faraazahmad/shellrb#47]
The tests for `mkdir` and `touch` fail stating permission denied.

```Bash
Failures:

  1) Mkdir.main given new directory creates the directory
     Failure/Error: Mkdir.main(["Mkdir.test"])

     Errno::EACCES:
       Permission denied @ dir_s_mkdir - Mkdir.test
     # ./lib/packages/mkdir.rb:28:in `main'
     # ./spec/packages/mkdir_spec.rb:8:in `block (4 levels) in <top (required)>'

  2) Mkdir.main given existing directory does not create the directory
     Failure/Error: FileUtils.mkdir("directorytest")

     Errno::EACCES:
       Permission denied @ dir_s_mkdir - directorytest
     # ./spec/packages/mkdir_spec.rb:17:in `block (4 levels) in <top (required)>'

  3) Touch.main given new file creates the file
     Failure/Error: Touch.main(["touch.test"])

     Errno::EACCES:
       Permission denied @ rb_sysopen - touch.test
     # ./lib/packages/touch.rb:28:in `write'
     # ./lib/packages/touch.rb:28:in `main'
     # ./spec/packages/touch_spec.rb:8:in `block (4 levels) in <top (required)>'

  4) Touch.main given existing file does nothing
     Failure/Error: File.write("touch.test", "")

     Errno::EACCES:
       Permission denied @ rb_sysopen - touch.test
     # ./spec/packages/touch_spec.rb:17:in `write'
     # ./spec/packages/touch_spec.rb:17:in `block (4 levels) in <top (required)>'

```

**Comment by faraazahmad** [comment]
Solved by @diego-asterisk.
